### ISSUE TITLE
Use configuration file to start KBS

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/kbs#78]
Now the parameters to start a KBS is eight https://github.com/confidential-containers/kbs/blob/main/src/kbs/src/main.rs#L25 . We might need to change the way to start KBS like kata-agent, s.t.
1. Define a configuration file
2. Read parameters from a given configuration file or degrate to a default one

**Comment by johananl** [comment]
Hi! I'm happy to take a look at this.

Looks like there is already support for a config file:

https://github.com/confidential-containers/kbs/blob/9902fb1a109bb9dfed791f7fc99eee44a5d6fd2d/src/kbs/src/main.rs#L65-L68

What should the new state look like compared to now? And which file format do we want to use (right now JSON seems to be used)?

**Comment by Xynnn007** [comment]
@johananl Hey, welcome to Confidential Containers! 
> Looks like there is already support for a config file:

Yes, it it. However, the parameters from the commandline are still too many as 

https://github.com/confidential-containers/kbs/blob/main/src/kbs/src/main.rs#L21C1-L58C2

My idea is that we use a single configuration file to set all the parameters, and we can also receive parameters from commandline. The logic might look like
- If `-c` parameter is given, KBS will use the given path as its configuration file
- If no `-c` parameter is given, by default KBS will look for a specific file as its configuration file, e.g. `/etc/kbs.config` or something
- If more parameters are given, KBS will give priority to the parameters entered on the command line. For example
    - `timeout=10` is set in the config file, while `-t 100` is given via parameter. Then `100` will be used.

In this way, it seems more "configuration as code". Could you share some point of views?

**Comment by surajssd** [comment]
I am not so sure about the configuration file approach.

Unlike kata-agent KBS is a pretty dynamic, container native application. OTOH kata-agent's config is pretty static and takes time to make any config changes and see them at play.

IMO for a container native application it should either support env vars or flags by default. So when a user deploys a KBS all they have to bother about is making changes in one config file like here:

https://github.com/confidential-containers/kbs/blob/9902fb1a109bb9dfed791f7fc99eee44a5d6fd2d/config/kubernetes/base/deployment.yaml#L21-L31

**Comment by Xynnn007** [comment]
> IMO for a container native application it should either support env vars or flags by default. So when a user deploys a KBS all they have to bother about is making changes in one config file like here:

Thanks for your ideas. I think if we use a single configuration file, we can leverage configmap mechanism in kubernetes to deploy KBS. A potential better way for the two aims is that we can also receive parameters from commandline to overwrite the settings from config file.

**Comment by johananl** [comment]
I get Xynnn007's point about too many CLI arguments. This is annoying especially when running the binary manually.

I also agree with Suraj that cloud-native apps tend to favor CLI args and env vars for their configuration.

AFAICT we could allow **both** approaches if we wanted, for example using the `config` crate: https://crates.io/crates/config

Maybe it would help to figure out what the main deployment method for KBS is, and make sure whatever approach we choose works best for that method. Is it mainly k8s? Do we also expect people to install KBS directly on VMs or bare metal servers?

**Comment by johananl** [comment]
Following an offline discussion with @mkulke, Magnus thinks it would make sense to support the following two methods of specifying KBS config:

1. CLI args **or** env vars where args have a higher precedence than vars.
2. A config file.

Using this approach, specifying a config file **precludes** specifying options in args or env vars. In other words, specifying `--config` in combination with e.g. `--socket` is an invalid state.

If there are no objections I'll take a stab at Magnus' approach and open a PR for review.

**Comment by johananl** [comment]
I've had some discussions with my colleagues offline about this. I'm summarizing the discussions here:

Right now the KBS config is split among CLI arguments as well as a config file.

https://github.com/confidential-containers/kbs/blob/2c6f6d04633a6eb1711c2041ce7cff6acce5a874/src/kbs/src/main.rs#L19-L58

https://github.com/confidential-containers/kbs/blob/2c6f6d04633a6eb1711c2041ce7cff6acce5a874/src/api/src/config.rs#L15-L55

Initially I wanted to consolidate the KBS config into **a single struct** and allow the user to populate this struct using one of the following two methods:

1. Reading a config file
1. Accepting CLI args and/or reading env vars

Method 1 is easy to implement: We accept just one CLI argument, `--config`, which points to a config file which in turn contains all the options.
Method 2 is also easy to implement: We use the [clap](https://crates.io/crates/clap) crate which can handle arbitrary combinations of CLI args and env vars.

However, if we want to consolidate the config then method 2 **must support the same options** as method 1. This is tricky because the config is nested rather than flat. Example:

https://github.com/confidential-containers/kbs/blob/2c6f6d04633a6eb1711c2041ce7cff6acce5a874/src/api/src/config.rs#L50-L54

https://github.com/confidential-containers/kbs/blob/2c6f6d04633a6eb1711c2041ce7cff6acce5a874/src/api/src/attestation/amber/mod.rs#L37-L43

How would we specify e.g. `amber` -> `base_url` via a CLI argument? We could go with `--amber-base-url`, but then we'd have a bunch of `--<method>-<option>` args for each of the supported attestation methods. The same goes for repository types and configurations: We'd quickly find ourselves with args such as `--localfs-dir-path`, `--localfs-foo` and `--localfs-bar` and then also `--remote-storage-dir-path`, `--remote-storage-baz` and `--remote-storage-qux`.

Lastly, specifying structured JSON values as strings in CLI args or env vars is VERY messy, and we already need to do this for `repository_description`:

https://github.com/confidential-containers/kbs/blob/2c6f6d04633a6eb1711c2041ce7cff6acce5a874/src/api/src/config.rs#L28

I tried to pass a value to `repository_description` and ran into escaping problems and other parsing issues.

All of the above makes me think it's undesirable or impractical to have **100% parity** between config file options and CLI args / env vars. Looking at other cloud native projects such as [Envoy](https://www.envoyproxy.io/docs/envoy/latest/operations/cli), it's clear that some options are only configurable on the CLI whereas others are only configurable via a config file (in the case of Envoy there are other alternatives to config files but they are the same in that the config is specified as **a data structure** rather than discrete config bits on the CLI or in env vars).

I've tried to generalize which options usually go in config files and which should be CLI args or env vars. Here are my thoughts:

- If there are just a few config options and the config scheme is *flat*, it's better to avoid config files altogether.
- If _nested_ config options are required, it's easier to specify nested options in a config file.
- Things which are tied to a *specific invocation* of the application (log level, debug mode, which config file to use) should be in CLI args and/or env vars.

What do you think @Xynnn007?

P. S. Please forgive the 📜

**Comment by Xynnn007** [comment]
Hi @johananl , thanks for the cool thought process!

> If there are just a few config options and the config scheme is flat, it's better to avoid config files altogether.
> If nested config options are required, it's easier to specify nested options in a config file.
> Things which are tied to a specific invocation of the application (log level, debug mode, which config file to use) should be in CLI args and/or env vars.

Agreed. I think it is a great summury. As you've mentioned, there are nested options in the config file like `amber_config`, which makes us SHOULD use a config file to avoid mess. Also, the CLI/ENVs are easy to read, which is helpful to specify the flags/specific invocation for app.

I prefer to think about what options we can move from CLI/ENV to the config files. In this way we can try to make the commandline easy to read and leave the other configurations structurialized inside the config file.

**Comment by johananl** [comment]
OK, great. I'll use the "what can we move to config file" approach and try to keep only invocation-specific options as CLI args. I'll also add env var support for all the CLI arg options.

**Comment by johananl** [comment]
PR #150 is ready for review. FWIW I'm still not sure which config params should reside in the config file and which should be CLI args 😬 I can't come up with a clear-cut definition of which params should go where and keep changing my opinion.

For now I went with the "put everything in the config file" approach in the PR because that's what we seem to have arrived at here, plus it may be easier to discuss with something concrete to look at. But there are clearly cases where it's nicer to have something (e.g. listening sockets) as a CLI arg.

Thoughts and opinions welcome (can be done directly on the PR 😉).
